### ISSUE TITLE
Docker: Add SAST stage 

### ISSUE THREAD

**Issue by joao10lima** [pipelinit/pipelinit-cli#75]
## Context

The SAST (Static application security testing) stage uses static analysis tools to improve overall code security. This step is distinct from the Lint step because of the security focus.

[semgrep](https://semgrep.dev/) is an open source fast SAST, with support for multiple languages. It can provide a high quality SAST stage for multiple stacks. Pipelinit should use it for supported stacks.

## Goal

Add a SAST stage for the Docker stack

## Implementation

- Add a template for the Docker stage called `sast.yml`
- Use the semgrep profile for specific for dockerfiles: https://semgrep.dev/p/dockerfile

You can use as basis an already made implementation:
- https://github.com/pipelinit/pipelinit-cli/pull/74/files#diff-07892e3cdb64511ca32b226e36d601e66cdac3a43015e3282daf263be609d2bb

**Comment by midhun1998** [comment]
Hi @joao10lima . I can pick this up if the feature is still open.

**Comment by joao10lima** [comment]
> Hi @joao10lima . I can pick this up if the feature is still open.

Hello @midhun1998, no problem it's still open, feel free to get ahead
