### ISSUE TITLE
Add Docker stack

### ISSUE THREAD

**Issue by oesgalha** [pipelinit/pipelinit-cli#8]
For "Dockerfile" files

Linter: [Hadolint](https://github.com/hadolint/hadolint)

**Comment by ayr-ton** [comment]
Is someone already working on this one?

**Comment by joao10lima** [comment]
Hey @ayr-ton, Included on the release https://github.com/pipelinit/pipelinit-cli/releases/tag/v0.1.0-rc.4

**Comment by ayr-ton** [comment]
@joao10lima just saw it on the README.md

This one will be one of my favorites <3
